### Feature Engineering

Whatever you do wih features, we call it as Feature Engineering.

* Feature Elimination    - dropping the features.
* Feature Addition       - adding some features.
* Feature Transformation - transforming the given feature values into an another scale - Log Tranformation, Sqrt Transformation..
* Feature Selection      - deciding which features are important out of many features and choosing that features for model building.

#### Feature Selection Techniques

* sklearn - SelectFromModel
* sklearn - RFE(ie,Recursive Feature Elimination)

## 1.Import Necessary Libraries

In [75]:
import pandas as pd

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import RFE,SelectFromModel
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier

import warnings
warnings.filterwarnings("ignore")


## 2.Load Datasets

In [16]:
breast_cancer=load_breast_cancer()
x=breast_cancer.data
y=breast_cancer.target

## 3.Data Undertanding

In [19]:
x.shape,y.shape

((569, 30), (569,))

## 4.Model Building

In [21]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=25,shuffle=True,stratify=y)

In [22]:
x_train.shape,y_train.shape

((455, 30), (455,))

In [23]:
x_test.shape,y_test.shape

((114, 30), (114,))

### 5.Model Training || 6.Model Testing || 7.Model Evaluation

In [51]:
rf_model=RandomForestClassifier(max_depth=7)
rf_model.fit(x_train,y_train)

y_pred_test=rf_model.predict(x_test)

print("Test Accuracy:",round(accuracy_score(y_test,y_pred_test),4))
print("Test Precision:",round(precision_score(y_test,y_pred_test),4))
print("Test recall:",round(recall_score(y_test,y_pred_test),4))
print("Test confusion matrix:\n",confusion_matrix(y_test,y_pred_test))

Test Accuracy: 0.9649
Test Precision: 0.9722
Test recall: 0.9722
Test confusion matrix:
 [[40  2]
 [ 2 70]]


In [39]:
rf_model.feature_importances_

array([0.03151999, 0.01132011, 0.04814683, 0.04467746, 0.00646057,
       0.01517554, 0.07138121, 0.10448323, 0.0029365 , 0.00444324,
       0.01745591, 0.00562553, 0.01554726, 0.04722388, 0.00240183,
       0.00433387, 0.00734671, 0.0042608 , 0.00405654, 0.0041244 ,
       0.08339142, 0.01872715, 0.16676259, 0.094729  , 0.01292921,
       0.00923145, 0.05806819, 0.08549717, 0.00840862, 0.00933377])

In [42]:
select_from_model=SelectFromModel(estimator=RandomForestClassifier(),max_features=None)
select_from_model.fit(x_train,y_train)

,"estimator estimator: objectThe base estimator from which the transformer is built.This can be both a fitted (if ``prefit`` is set to True)or a non-fitted estimator. The estimator should have a``feature_importances_`` or ``coef_`` attribute after fitting.Otherwise, the ``importance_getter`` parameter should be used.",RandomForestClassifier()
,"threshold threshold: str or float, default=NoneThe threshold value to use for feature selection. Features whoseabsolute importance value is greater or equal are kept while the othersare discarded. If ""median"" (resp. ""mean""), then the ``threshold`` valueis the median (resp. the mean) of the feature importances. A scalingfactor (e.g., ""1.25*mean"") may also be used. If None and if theestimator has a parameter penalty set to l1, either explicitlyor implicitly (e.g, Lasso), the threshold used is 1e-5.Otherwise, ""mean"" is used by default.",None
,"prefit prefit: bool, default=FalseWhether a prefit model is expected to be passed into the constructordirectly or not.If `True`, `estimator` must be a fitted estimator.If `False`, `estimator` is fitted and updated by calling`fit` and `partial_fit`, respectively.",False
,"norm_order norm_order: non-zero int, inf, -inf, default=1Order of the norm used to filter the vectors of coefficients below``threshold`` in the case where the ``coef_`` attribute of theestimator is of dimension 2.",1
,"max_features max_features: int, callable, default=NoneThe maximum number of features to select.- If an integer, then it specifies the maximum number of features to allow.- If a callable, then it specifies how to calculate the maximum number of features allowed. The callable will receive `X` as input: `max_features(X)`.- If `None`, then all features are kept.To only select based on ``max_features``, set ``threshold=-np.inf``... versionadded:: 0.20.. versionchanged:: 1.1 `max_features` accepts a callable.",None
,"importance_getter importance_getter: str or callable, default='auto'If 'auto', uses the feature importance either through a ``coef_``attribute or ``feature_importances_`` attribute of estimator.Also accepts a string that specifies an attribute name/pathfor extracting feature importance (implemented with `attrgetter`).For example, give `regressor_.coef_` in case of:class:`~sklearn.compose.TransformedTargetRegressor` or`named_steps.clf.feature_importances_` in case of:class:`~sklearn.pipeline.Pipeline` with its last step named `clf`.If `callable`, overrides the default feature importance getter.The callable is passed with the fitted estimator and it shouldreturn importance for each feature... versionadded:: 0.24",'auto'
Name,Type,Value
"estimator_ estimator_: estimatorThe base estimator from which the transformer is built. This attributeexist only when `fit` has been called.- If `prefit=True`, it is a deep copy of `estimator`.- If `prefit=False`, it is a clone of `estimator` and fit on the data passed to `fit` or `partial_fit`.",RandomForestClassifier,RandomForestClassifier()
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`. Only defined if theunderlying estimator exposes such an attribute when fit... versionadded:: 0.24,int,30
threshold_ threshold_: floatThe threshold value used for feature selection.,float64,0.03333
,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100


In [45]:
select_from_model.get_support()

array([False, False, False,  True, False, False,  True,  True, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True, False,  True,  True, False, False,  True,
        True, False, False])

In [46]:
breast_cancer.feature_names[select_from_model.get_support()]

array(['mean area', 'mean concavity', 'mean concave points', 'area error',
       'worst radius', 'worst perimeter', 'worst area', 'worst concavity',
       'worst concave points'], dtype='<U23')

In [48]:
x_train_select_from_model=select_from_model.transform(x_train)
x_test_select_from_model=select_from_model.transform(x_test)

In [50]:
x_train_select_from_model.shape,x_test_select_from_model.shape

((455, 9), (114, 9))

In [55]:
def runRandomForestClassifier(x_train,x_test,y_train,y_test):
    rf_model=RandomForestClassifier(max_depth=7,random_state=123)
    rf_model.fit(x_train,y_train)
    
    y_pred_test=rf_model.predict(x_test)
    
    print("Test Accuracy:",round(accuracy_score(y_test,y_pred_test),4))
    print("Test Precision:",round(precision_score(y_test,y_pred_test),4))
    print("Test recall:",round(recall_score(y_test,y_pred_test),4))
    print("Test confusion matrix:\n",confusion_matrix(y_test,y_pred_test))

In [56]:
%%time
runRandomForestClassifier(x_train,x_test,y_train,y_test)

Test Accuracy: 0.9737
Test Precision: 0.9859
Test recall: 0.9722
Test confusion matrix:
 [[41  1]
 [ 2 70]]
CPU times: total: 625 ms
Wall time: 787 ms


In [57]:
%%time
runRandomForestClassifier(x_train_select_from_model,x_test_select_from_model,y_train,y_test)

Test Accuracy: 0.9649
Test Precision: 0.9857
Test recall: 0.9583
Test confusion matrix:
 [[41  1]
 [ 3 69]]
CPU times: total: 391 ms
Wall time: 371 ms


## 2nd Techniques RFE(Recursive Feature Elimination)

In [63]:
rfe_model=RFE(estimator = RandomForestClassifier(), n_features_to_select=12)
rfe_model.fit(x_train,y_train)

,"estimator estimator: ``Estimator`` instanceA supervised learning estimator with a ``fit`` method that providesinformation about feature importance(e.g. `coef_`, `feature_importances_`).",RandomForestClassifier()
,"n_features_to_select n_features_to_select: int or float, default=NoneThe number of features to select. If `None`, half of the features areselected. If integer, the parameter is the absolute number of featuresto select. If float between 0 and 1, it is the fraction of features toselect... versionchanged:: 0.24 Added float values for fractions.",12
,"step step: int or float, default=1If greater than or equal to 1, then ``step`` corresponds to the(integer) number of features to remove at each iteration.If within (0.0, 1.0), then ``step`` corresponds to the percentage(rounded down) of features to remove at each iteration.",1
,"verbose verbose: int, default=0Controls verbosity of output.",0
,"importance_getter importance_getter: str or callable, default='auto'If 'auto', uses the feature importance either through a `coef_`or `feature_importances_` attributes of estimator.Also accepts a string that specifies an attribute name/pathfor extracting feature importance (implemented with `attrgetter`).For example, give `regressor_.coef_` in case of:class:`~sklearn.compose.TransformedTargetRegressor` or`named_steps.clf.feature_importances_` in case ofclass:`~sklearn.pipeline.Pipeline` with its last step named `clf`.If `callable`, overrides the default feature importance getter.The callable is passed with the fitted estimator and it shouldreturn importance for each feature... versionadded:: 0.24",'auto'
Name,Type,Value
"classes_ classes_: ndarray of shape (n_classes,)The classes labels. Only available when `estimator` is a classifier.","ndarray[int64](2,)","[0,1]"
estimator_ estimator_: ``Estimator`` instanceThe fitted estimator used to select features.,RandomForestClassifier,RandomForestClassifier()
n_features_ n_features_: intThe number of selected features.,int64,np.int64(12)
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`. Only defined if theunderlying estimator exposes such an attribute when fit... versionadded:: 0.24,int,30
"ranking_ ranking_: ndarray of shape (n_features,)The feature ranking, such that ``ranking_[i]`` corresponds to theranking position of the i-th feature. Selected (i.e., estimatedbest) features are assigned rank 1.","ndarray[int64](30,)","[ 1, 2, 1,..., 1, 4,12]"


In [64]:
rfe_model.get_support()

array([ True, False,  True,  True, False, False,  True,  True, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False,  True,
        True, False, False])

In [65]:
breast_cancer.feature_names[rfe_model.get_support()]

array(['mean radius', 'mean perimeter', 'mean area', 'mean concavity',
       'mean concave points', 'area error', 'worst radius',
       'worst texture', 'worst perimeter', 'worst area',
       'worst concavity', 'worst concave points'], dtype='<U23')

In [67]:
x_train_rfe_model=rfe_model.transform(x_train)
x_test_rfe_model=rfe_model.transform(x_test)

In [68]:
x_train_rfe_model.shape,x_test_rfe_model.shape

((455, 12), (114, 12))

In [81]:
%%time
runRandomForestClassifier(x_train,x_test,y_train,y_test)

Test Accuracy: 0.9737
Test Precision: 0.9859
Test recall: 0.9722
Test confusion matrix:
 [[41  1]
 [ 2 70]]
CPU times: total: 625 ms
Wall time: 1.1 s


In [82]:
%%time
runRandomForestClassifier(x_train_rfe_model,x_test_rfe_model,y_train,y_test)

Test Accuracy: 0.9649
Test Precision: 0.9857
Test recall: 0.9583
Test confusion matrix:
 [[41  1]
 [ 3 69]]
CPU times: total: 547 ms
Wall time: 567 ms


## 3. Take the important features from GradientBoosting and train it with in RandomForest Algorithm

In [83]:
rfe_model=RFE(estimator = GradientBoostingClassifier(), n_features_to_select=12)
rfe_model.fit(x_train,y_train)

,"estimator estimator: ``Estimator`` instanceA supervised learning estimator with a ``fit`` method that providesinformation about feature importance(e.g. `coef_`, `feature_importances_`).",GradientBoostingClassifier()
,"n_features_to_select n_features_to_select: int or float, default=NoneThe number of features to select. If `None`, half of the features areselected. If integer, the parameter is the absolute number of featuresto select. If float between 0 and 1, it is the fraction of features toselect... versionchanged:: 0.24 Added float values for fractions.",12
,"step step: int or float, default=1If greater than or equal to 1, then ``step`` corresponds to the(integer) number of features to remove at each iteration.If within (0.0, 1.0), then ``step`` corresponds to the percentage(rounded down) of features to remove at each iteration.",1
,"verbose verbose: int, default=0Controls verbosity of output.",0
,"importance_getter importance_getter: str or callable, default='auto'If 'auto', uses the feature importance either through a `coef_`or `feature_importances_` attributes of estimator.Also accepts a string that specifies an attribute name/pathfor extracting feature importance (implemented with `attrgetter`).For example, give `regressor_.coef_` in case of:class:`~sklearn.compose.TransformedTargetRegressor` or`named_steps.clf.feature_importances_` in case ofclass:`~sklearn.pipeline.Pipeline` with its last step named `clf`.If `callable`, overrides the default feature importance getter.The callable is passed with the fitted estimator and it shouldreturn importance for each feature... versionadded:: 0.24",'auto'
Name,Type,Value
"classes_ classes_: ndarray of shape (n_classes,)The classes labels. Only available when `estimator` is a classifier.","ndarray[int64](2,)","[0,1]"
estimator_ estimator_: ``Estimator`` instanceThe fitted estimator used to select features.,GradientBoostingClassifier,GradientBoostingClassifier()
n_features_ n_features_: intThe number of selected features.,int64,np.int64(12)
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`. Only defined if theunderlying estimator exposes such an attribute when fit... versionadded:: 0.24,int,30
"ranking_ ranking_: ndarray of shape (n_features,)The feature ranking, such that ``ranking_[i]`` corresponds to theranking position of the i-th feature. Selected (i.e., estimatedbest) features are assigned rank 1.","ndarray[int64](30,)","[12, 1, 7,..., 1, 1,14]"


In [84]:
rfe_model.get_support()

array([False,  True, False, False, False, False, False,  True, False,
        True,  True, False, False,  True, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False,  True,
        True,  True, False])

In [85]:
breast_cancer.feature_names[rfe_model.get_support()]

array(['mean texture', 'mean concave points', 'mean fractal dimension',
       'radius error', 'area error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst concavity',
       'worst concave points', 'worst symmetry'], dtype='<U23')

In [86]:
x_train_rfe_model=rfe_model.transform(x_train)
x_test_rfe_model=rfe_model.transform(x_test)

In [87]:
x_train_rfe_model.shape,x_test_rfe_model.shape

((455, 12), (114, 12))

In [88]:
%%time
runRandomForestClassifier(x_train,x_test,y_train,y_test)

Test Accuracy: 0.9737
Test Precision: 0.9859
Test recall: 0.9722
Test confusion matrix:
 [[41  1]
 [ 2 70]]
CPU times: total: 500 ms
Wall time: 595 ms


In [90]:
%%time
runRandomForestClassifier(x_train_rfe_model,x_test_rfe_model,y_train,y_test)

Test Accuracy: 0.9561
Test Precision: 0.9718
Test recall: 0.9583
Test confusion matrix:
 [[40  2]
 [ 3 69]]
CPU times: total: 531 ms
Wall time: 548 ms


### 4.How to choose the optimal no of features to train my model?


In [ ]:
def runRandomForestClassifier(x_train,x_test,y_train,y_test):
    rf_model=RandomForestClassifier(max_depth=7,random_state=123)
    rf_model.fit(x_train,y_train)
    
    y_pred_test=rf_model.predict(x_test)
    
    print("Test Accuracy:",round(accuracy_score(y_test,y_pred_test),4))
    print("Test Precision:",round(precision_score(y_test,y_pred_test),4))
    print("Test recall:",round(recall_score(y_test,y_pred_test),4))
    print("Test confusion matrix:\n",confusion_matrix(y_test,y_pred_test))

In [91]:
for i in range(1,31):
    rfe_model=RFE(estimator = GradientBoostingClassifier(), n_features_to_select=i)
    rfe_model.fit(x_train,y_train)
    x_train_rfe_model=rfe_model.transform(x_train)
    x_test_rfe_model=rfe_model.transform(x_test)
    print("Selected Feature : ",i)
    runRandomForestClassifier(x_train_rfe_model,x_test_rfe_model,y_train,y_test)
    print("---------------------------------------------------------")
    


  

Selected Feature :  1
Test Accuracy: 0.8947
Test Precision: 0.9286
Test recall: 0.9028
Test confusion matrix:
 [[37  5]
 [ 7 65]]
---------------------------------------------------------
Selected Feature :  2
Test Accuracy: 0.9123
Test Precision: 0.9429
Test recall: 0.9167
Test confusion matrix:
 [[38  4]
 [ 6 66]]
---------------------------------------------------------
Selected Feature :  3
Test Accuracy: 0.9474
Test Precision: 0.9583
Test recall: 0.9583
Test confusion matrix:
 [[39  3]
 [ 3 69]]
---------------------------------------------------------
Selected Feature :  4
Test Accuracy: 0.9649
Test Precision: 0.9722
Test recall: 0.9722
Test confusion matrix:
 [[40  2]
 [ 2 70]]
---------------------------------------------------------
Selected Feature :  5
Test Accuracy: 0.9737
Test Precision: 0.9859
Test recall: 0.9722
Test confusion matrix:
 [[41  1]
 [ 2 70]]
---------------------------------------------------------
Selected Feature :  6
Test Accuracy: 0.9737
Test Precision: 

### THE END